events {}

http {
  server {
    listen 80;
    server_name alarcon.bank;

    location /transfers/ {
      # The host alarcon.bank here is the same value in the docker-compose file
      proxy_pass http://alarcon.bank:3000;
    }
  }
}